#!/usr/bin/env python3
"""Prepare RTL artifacts for the hierarchical AMOEBA physical flow.

The generated PyMTL Verilog is monolithic. This helper finds the generated
CgraWithLoopController module name, writes it into a Tcl fragment, and emits a
copy of the top RTL with that one core module definition removed. The top-level
DC run then resolves the core instance from the pre-synthesized core DDC.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


MODULE_RE = re.compile(r"^module\s+([A-Za-z_][A-Za-z0-9_\$]*)\b", re.MULTILINE)


def find_core_module(rtl_text: str) -> str:
    modules = MODULE_RE.findall(rtl_text)
    core_modules = [name for name in modules if name.startswith("CgraWithLoopControllerRTL__")]
    if len(core_modules) != 1:
        raise RuntimeError(
            "Expected exactly one CgraWithLoopControllerRTL module, "
            f"found {len(core_modules)}: {core_modules}"
        )
    return core_modules[0]


def remove_module_definition(rtl_text: str, module_name: str) -> str:
    lines = rtl_text.splitlines(keepends=True)
    out: list[str] = []
    skipping = False
    removed = False

    for line in lines:
        if not skipping and re.match(rf"^module\s+{re.escape(module_name)}\b", line):
            skipping = True
            removed = True
            out.append(f"// Removed {module_name}; resolved from synthesized DDC.\n")
            continue

        if skipping:
            if line.strip() == "endmodule":
                skipping = False
            continue

        out.append(line)

    if skipping:
        raise RuntimeError(f"Reached EOF while removing module {module_name}")
    if not removed:
        raise RuntimeError(f"Did not find module definition for {module_name}")
    return "".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rtl", required=True, type=Path)
    parser.add_argument("--work-dir", required=True, type=Path)
    parser.add_argument("--top-only-rtl", required=True, type=Path)
    parser.add_argument("--module-names-tcl", required=True, type=Path)
    args = parser.parse_args()

    rtl_text = args.rtl.read_text()
    core_module = find_core_module(rtl_text)

    args.work_dir.mkdir(parents=True, exist_ok=True)
    args.top_only_rtl.parent.mkdir(parents=True, exist_ok=True)
    args.module_names_tcl.parent.mkdir(parents=True, exist_ok=True)

    args.top_only_rtl.write_text(remove_module_definition(rtl_text, core_module))
    args.module_names_tcl.write_text(
        "# Generated by prepare_hier_rtl.py.\n"
        f"set CORE_MODULE \"{core_module}\"\n"
    )

    print(f"Core module: {core_module}")
    print(f"Top-only RTL: {args.top_only_rtl}")
    print(f"Module-name Tcl: {args.module_names_tcl}")


if __name__ == "__main__":
    main()
